name: Server

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    uses: giocaizzi/python-dev-actions/.github/workflows/deployment.yml@toml
    secrets: inherit
    with:
        subdir : repomanager
        python-version: "3.10"
        python-tested-versions: "['3.10','3.11','3.12']"
        python-package-type: "pyproject.toml"
      